/**
 * GENERATED by scripts/build-tokens.mjs — do not edit by hand.
 * Source: Figma EhpRiGZ5eJnBb132X9zewg, synced 2026-08-23.
 *
 * Raw generated shape. Application code should import from ../tokens/theme
 * instead — theme.ts is the stable adapter over this file.
 */

export const color = {
  brand: {
    "50": "#e2e9e3",
    "100": "#d0dacf",
    "200": "#77b691",
    "300": "#579a74",
    "400": "#387f56",
    "500": "#186338",
    "600": "#134f2d",
    "700": "#1e3e2b",
    "800": "#071e11",
    "900": "#05140b",
  },
  secondary: {
    "50": "#fefefd",
    "100": "#fbf8f7",
    "200": "#f6f1ee",
    "300": "#f8f7f2",
    "400": "#f6f4ee",
    "500": "#f4f1ea",
    "600": "#eae6db",
    "700": "#dbd5c8",
    "800": "#c2b9a6",
    "900": "#aa9e83",
  },
  tertiary: {
    "50": "#fdfbfb",
    "100": "#fbf8f7",
    "200": "#f6f1ee",
    "300": "#f2e9e6",
    "400": "#ede2dd",
    "500": "#e9dbd5",
    "600": "#cebcb5",
    "700": "#b39e95",
    "800": "#997f74",
    "900": "#7e6154",
  },
  grey: {
    "50": "#fcfcfd",
    "100": "#e6e7ea",
    "200": "#cdcfd6",
    "300": "#b3b8c1",
    "400": "#9aa0ad",
    "500": "#818898",
    "600": "#676d7a",
    "700": "#4d525b",
    "800": "#34363d",
    "900": "#1a1b1e",
  },
  neutral: {
    white: "#ffffff",
    black: "#1a1a1a",
  },
  info: {
    "100": "#d8e5ed",
    "200": "#b0cbdb",
    "300": "#89b0c9",
    "400": "#6196b7",
    "500": "#3a7ca5",
    "600": "#2e6384",
    "700": "#234a63",
    "800": "#173242",
    "900": "#0c1921",
  },
  success: {
    "100": "#dee8de",
    "200": "#bed0be",
    "300": "#9db99d",
    "400": "#7da17d",
    "500": "#5c8a5c",
    "600": "#4a6e4a",
    "700": "#375337",
    "800": "#253725",
    "900": "#121c12",
  },
  warning: {
    "100": "#f6ecd1",
    "200": "#eed9a2",
    "300": "#e5c674",
    "400": "#ddb345",
    "500": "#d4a017",
    "600": "#aa8012",
    "700": "#7f600e",
    "800": "#554009",
    "900": "#2a2005",
  },
  error: {
    "100": "#f7dada",
    "200": "#efb5b5",
    "300": "#e68f8f",
    "400": "#de6a6a",
    "500": "#d64545",
    "600": "#ab3737",
    "700": "#802929",
    "800": "#561c1c",
    "900": "#2b0e0e",
  },
  sage: {
    "500": "#91aa83",
  },
  taupe: {
    "500": "#7d715e",
  },
  text: {
    default: "#4d525b",
    subtle: "#7d715e",
    subtlest: "#818898",
    inverse: {
      default: "#b3b8c1",
      subtle: "#818898",
      subtlest: "#4d525b",
    },
    disabled: "#9aa0ad",
    brand: {
      subtle: "#aa9e83",
      default: "#186338",
      bold: "#1e3e2b",
    },
    link: {
      default: "#3a7ca5",
      bold: "#234a63",
    },
    success: {
      default: "#5c8a5c",
      bold: "#375337",
    },
    danger: {
      default: "#d64545",
      bold: "#802929",
    },
    warning: {
      default: "#d4a017",
      bold: "#7f600e",
    },
    stable: {
      white: "#ffffff",
      black: "#1a1a1a",
    },
  },
  background: {
    default: "#f4f1ea",
    hover: "#eae6db",
    pressed: "#dbd5c8",
    inverse: {
      default: "#aa9e83",
      hover: "#c2b9a6",
      pressed: "#dbd5c8",
    },
    disabled: "#cdcfd6",
    brand: {
      subtle: "#e2e9e3",
      default: "#186338",
      hover: "#134f2d",
      pressed: "#1e3e2b",
      disabled: "#77b691",
    },
    information: {
      default: "#3a7ca5",
      subtle: "#d8e5ed",
    },
    warning: {
      default: "#d4a017",
      subtle: "#f6ecd1",
    },
    danger: {
      default: "#d64545",
      subtle: "#f7dada",
    },
    success: {
      default: "#5c8a5c",
      subtle: "#dee8de",
    },
  },
  border: {
    default: "#b3b8c1",
    subtle: "#cdcfd6",
    subtlest: "#e6e7ea",
    brand: {
      subtle: "#d0dacf",
      default: "#186338",
      bold: "#134f2d",
    },
    link: {
      default: "#3a7ca5",
    },
    success: {
      default: "#5c8a5c",
    },
    danger: {
      default: "#d64545",
    },
    warning: {
      default: "#d4a017",
    },
  },
} as const;

export const elevation = {
  surface: {
    default: "#f4f1ea",
    raised: "#eae6db",
    overlay: "#dbd5c8",
    deep: "#c2b9a6",
    deepest: "#aa9e83",
  },
} as const;

export const space = {
  "4": 4,
  "8": 8,
  "12": 12,
  "16": 16,
  "24": 24,
  "32": 32,
  "48": 48,
  "64": 64,
  "80": 80,
  "96": 96,
} as const;

export const radius = {
  none: 0,
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  "2xl": 24,
  "3xl": 32,
  full: 99999,
} as const;

export const typography = {
  fonts: {
    display: "PlayfairDisplay-Medium",
    button: "PlayfairDisplay-Medium",
    body: "Inter-Regular",
    medium: "Inter-Medium",
    semiBold: "Inter-SemiBold",
  },
  heading: {
    h1: {
      fontFamily: "PlayfairDisplay-Medium",
      fontSize: 30,
      lineHeight: 39,
      lineHeightPct: 130,
    },
    h2: {
      fontFamily: "PlayfairDisplay-Medium",
      fontSize: 24,
      lineHeight: 36,
      lineHeightPct: 150,
    },
    h3: {
      fontFamily: "PlayfairDisplay-Medium",
      fontSize: 18,
      lineHeight: 25.2,
      lineHeightPct: 140,
    },
    h4: {
      fontFamily: "PlayfairDisplay-Medium",
      fontSize: 16,
      lineHeight: 24,
      lineHeightPct: 150,
    },
    h5: {
      fontFamily: "PlayfairDisplay-Medium",
      fontSize: 14,
      lineHeight: 22.4,
      lineHeightPct: 160,
    },
    h6: {
      fontFamily: "PlayfairDisplay-Medium",
      fontSize: 12,
      lineHeight: 16.8,
      lineHeightPct: 140,
    },
  },
  paragraph: {
    p1: {
      fontFamily: "Inter-Regular",
      fontSize: 16,
      lineHeight: 27.2,
      lineHeightPct: 170,
    },
    p2: {
      fontFamily: "Inter-Regular",
      fontSize: 14,
      lineHeight: 21.7,
      lineHeightPct: 155,
    },
    p3: {
      fontFamily: "Inter-Regular",
      fontSize: 12,
      lineHeight: 18.6,
      lineHeightPct: 155,
    },
  },
  subhead: {
    s1: {
      fontFamily: "Inter-Medium",
      fontSize: 16,
      lineHeight: 24.8,
      lineHeightPct: 155,
    },
    s2: {
      fontFamily: "Inter-Medium",
      fontSize: 14,
      lineHeight: 21.7,
      lineHeightPct: 155,
    },
    s3: {
      fontFamily: "Inter-Medium",
      fontSize: 12,
      lineHeight: 18.6,
      lineHeightPct: 155,
    },
  },
  caption: {
    c1: {
      fontFamily: "Inter-SemiBold",
      fontSize: 10,
      lineHeight: 15.5,
      lineHeightPct: 155,
    },
    c2: {
      fontFamily: "Inter-Medium",
      fontSize: 10,
      lineHeight: 15.5,
      lineHeightPct: 155,
    },
    c3: {
      fontFamily: "Inter-Regular",
      fontSize: 10,
      lineHeight: 15.5,
      lineHeightPct: 155,
    },
  },
} as const;

export const shadows = {
  m: {
    shadowColor: "#0d0d12",
    shadowOffset: {
      width: 1,
      height: 4,
    },
    shadowOpacity: 0.05,
    shadowRadius: 27,
    elevation: 7,
    _figma: {
      radius: 25,
      spread: 2,
      note: "shadowRadius = radius + spread; RN has no spread",
    },
  },
  l: {
    shadowColor: "#0d0d12",
    shadowOffset: {
      width: 1,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 27,
    elevation: 7,
    _figma: {
      radius: 25,
      spread: 2,
      note: "shadowRadius = radius + spread; RN has no spread",
    },
  },
  up: {
    shadowColor: "#000000",
    shadowOffset: {
      width: -2,
      height: 0,
    },
    shadowOpacity: 0.03,
    shadowRadius: 30,
    elevation: 8,
    _figma: {
      radius: 25,
      spread: 5,
      note: "shadowRadius = radius + spread; RN has no spread",
    },
  },
  down: {
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.03,
    shadowRadius: 17,
    elevation: 4,
    _figma: {
      radius: 15,
      spread: 2,
      note: "shadowRadius = radius + spread; RN has no spread",
    },
  },
} as const;

export const tokens = { color, elevation, space, radius, typography, shadows } as const;
export type Tokens = typeof tokens;
