#!/bin/sh
# home-v2.html reuses the coded Assist phones (.gp, assist.html) in its Sprout Assist carousel.
# assist-landing.css also styles the whole Assist page (body, :root, sections), so it can't be linked
# from home-v2. This copies only the phone rules. Re-run after editing the .gp block in assist-landing.css.
cd "$(dirname "$0")/.." || exit 1
start=$(grep -n '^\.art:has(\.gp)' assist-landing.css | cut -d: -f1)
{
  echo "/* GENERATED by review/sync-v2-gp.sh from assist-landing.css line $start to end. Do not edit here. */"
  tail -n +"$start" assist-landing.css
} > home-v2-gp.css
echo "home-v2-gp.css: $(wc -l < home-v2-gp.css) lines"
